import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const material=(color,roughness=.85)=>new THREE.MeshStandardMaterial({color,roughness});
export class TrainWorld {
  constructor(canvas,game){
    this.canvas=canvas;this.game=game;this.view='cab';this.scene=new THREE.Scene();
    this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.2;
    this.camera=new THREE.PerspectiveCamera(67,1,.07,1300);this.scene.add(new THREE.HemisphereLight(0xd6edf2,0x56624d,2));const sun=new THREE.DirectionalLight(0xffe0b4,3);sun.position.set(-80,140,100);this.scene.add(sun);
    this.trainRoot=new THREE.Group();this.cabRoot=new THREE.Group();this.scene.add(this.trainRoot,this.cabRoot);this.trainRoot.visible=false;
    this.environment=new THREE.Group();this.scene.add(this.environment);this.assetStatus={train:'loading',cab:'loading'};this.assetsReady=false;
    this.addLiveInstruments();this.loadAssets();this.rebuild();this.resize();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement);
  }
  loadAssets(){const loader=new GLTFLoader();for(const [kind,file,root] of [['train','train.glb',this.trainRoot],['cab','train-cab.glb',this.cabRoot]]){
    loader.load(`${import.meta.env.BASE_URL}models/${file}`,gltf=>{root.add(gltf.scene);gltf.scene.traverse(n=>{if(kind==='cab'&&n.name==='TractionLever')this.tractionLever=n;if(kind==='cab'&&n.name==='BrakeLever')this.brakeLever=n;if(n.isMesh){n.frustumCulled=false;if(n.material?.map)n.material.map.anisotropy=Math.min(4,this.renderer.capabilities.getMaxAnisotropy());if(n.material?.name?.includes('glazing')){n.material.opacity=.06;n.material.depthWrite=false;}}});this.assetStatus[kind]='ready';this.assetsReady=Object.values(this.assetStatus).every(v=>v==='ready');window.dispatchEvent(new CustomEvent('train-assets',{detail:this.assetStatus}));},undefined,error=>{this.assetStatus[kind]='error';window.dispatchEvent(new CustomEvent('train-assets',{detail:this.assetStatus}));console.error(`無法載入 ${file}`,error);});
  }}
  addLiveInstruments(){this.instrumentCanvas=document.createElement('canvas');this.instrumentCanvas.width=1024;this.instrumentCanvas.height=180;this.instrumentTexture=new THREE.CanvasTexture(this.instrumentCanvas);this.instrumentTexture.colorSpace=THREE.SRGBColorSpace;const screen=new THREE.Mesh(new THREE.PlaneGeometry(1.48,.26),new THREE.MeshBasicMaterial({map:this.instrumentTexture}));screen.rotation.y=Math.PI;screen.position.set(0,.83,.452);this.cabRoot.add(screen);this.instrumentLast=0;}
  paintInstruments(){const s=this.game.getState(),ctx=this.instrumentCanvas.getContext('2d');ctx.fillStyle='#143844';ctx.fillRect(0,0,1024,180);ctx.strokeStyle='#649689';ctx.lineWidth=3;ctx.strokeRect(8,8,1008,164);const labels=['SPEED km/h','POWER','BRAKE kPa','SIGNAL'],values=[Math.abs(s.speed).toFixed(0),String(s.controls.throttle),s.pressure.toFixed(0),s.signal.toUpperCase()];for(let i=0;i<4;i++){const x=45+i*250;ctx.fillStyle='#9cbbb1';ctx.font='22px monospace';ctx.fillText(labels[i],x,45);ctx.fillStyle=i===3?{red:'#ff7765',yellow:'#ffd075',green:'#7bebbc'}[s.signal]:'#e4f3d5';ctx.font=i===3?'bold 40px monospace':'bold 72px monospace';ctx.fillText(values[i],x,130);}this.instrumentTexture.needsUpdate=true;}
  point(s){const r=this.game.route;return new THREE.Vector3(Math.sin(s/200)*r.curve,Math.sin(s/140)*r.grade*140+1.0,s);}
  tangent(s){return this.point(s+1).sub(this.point(s-1)).normalize();}
  rotation(s){const t=this.tangent(s);return Math.atan2(t.x,t.z);}
  addBox(size,pos,mat,parent=this.environment){const m=new THREE.Mesh(new THREE.BoxGeometry(...size),mat);m.position.copy(pos);parent.add(m);return m;}
  makeInstances(geometry,mat,items){const mesh=new THREE.InstancedMesh(geometry,mat,items.length);const d=new THREE.Object3D();items.forEach((v,i)=>{d.position.copy(v.pos);d.rotation.set(v.rx||0,v.angle||0,0);d.scale.set(...(v.scale||[1,1,1]));d.updateMatrix();mesh.setMatrixAt(i,d.matrix);});this.environment.add(mesh);return mesh;}
  label(text){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#183e49';ctx.fillRect(0,0,512,128);ctx.fillStyle='#f1e9cb';ctx.font='bold 44px sans-serif';ctx.textAlign='center';ctx.fillText(text,256,80);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return new THREE.MeshBasicMaterial({map:t});}
  rebuild(){
    // Dispose only the replaced landscape; loaded GLB assets remain in memory.
    this.environment.traverse(n=>{if(n.isMesh){n.geometry?.dispose();if(n.material?.map)n.material.map.dispose();}});this.environment.clear();const r=this.game.route;this.scene.background=new THREE.Color(r.sky);this.scene.fog=new THREE.Fog(r.fog,170,780);
    const grass=material(r.ground),stone=material(r.rail),steel=material(0x758789,.35),wood=material(0x555448),concrete=material(0xb6b6a4),trees=material(r.theme==='forest'?0x345a43:0x4d7955),leaf=material(0x608866);
    this.addBox([2300,2,3200],new THREE.Vector3(0,-1.5,950),grass);
    const sleepers=[],left=[],right=[],ballast=[];for(let s=-100;s<1550;s+=1.25){const p=this.point(s),angle=this.rotation(s);sleepers.push({pos:p.clone().add(new THREE.Vector3(0,-.03,0)),angle});if(s%5===0){for(const [items,offset] of [[left,-.5335],[right,.5335]]){const off=new THREE.Vector3(offset,0,0).applyAxisAngle(new THREE.Vector3(0,1,0),angle);items.push({pos:p.clone().add(off).add(new THREE.Vector3(0,.17,2.5)),angle});}ballast.push({pos:p.clone().add(new THREE.Vector3(0,-.22,2.5)),angle});}}
    this.makeInstances(new THREE.BoxGeometry(2.1,.17,.2),wood,sleepers);this.makeInstances(new THREE.BoxGeometry(.065,.17,5.08),steel,left);this.makeInstances(new THREE.BoxGeometry(.065,.17,5.08),steel,right);this.makeInstances(new THREE.BoxGeometry(3.4,.42,5.12),stone,ballast);
    const shrubs=[],trunks=[],buildings=[];for(let s=-90;s<1550;s+=18){for(let side of [-1,1]){const p=this.point(s);const offset=10+Math.abs(Math.sin(s*2))*36;p.x+=side*offset;const height=5+Math.abs(Math.sin(s))*7;if(r.theme==='city'){buildings.push({pos:p.clone().add(new THREE.Vector3(0,height/2-1,0)),scale:[6+Math.abs(Math.sin(s))*8,height,7]});}else{trunks.push({pos:p.clone().add(new THREE.Vector3(0,1,0)),scale:[.4,3,.4]});shrubs.push({pos:p.clone().add(new THREE.Vector3(0,height/2+1,0)),scale:[3,height*.75,3]});}}}
    this.makeInstances(new THREE.CylinderGeometry(.5,.65,1,5),material(0x64533e),trunks);this.makeInstances(new THREE.ConeGeometry(1,1,7),trees,shrubs);
    if(buildings.length){this.makeInstances(new THREE.BoxGeometry(1,1,1),material(0xa4b4b7),buildings);const windows=[];buildings.forEach(v=>{for(let y=1;y<v.scale[1]-1;y+=2.8)windows.push({pos:v.pos.clone().add(new THREE.Vector3(-v.scale[0]/2-.01,y-v.scale[1]/2,0)),scale:[.04,.9,v.scale[2]*.8]});});this.makeInstances(new THREE.BoxGeometry(1,1,1),material(0x456672,.3),windows);}
    if(r.theme==='coast'){const sea=new THREE.Mesh(new THREE.PlaneGeometry(700,3000),new THREE.MeshStandardMaterial({color:0x438f9e,roughness:.27,metalness:.3}));sea.rotation.x=-Math.PI/2;sea.position.set(-400,-.45,900);this.environment.add(sea);const waves=[];for(let z=-100;z<1400;z+=24)waves.push({pos:new THREE.Vector3(-80-Math.abs(Math.sin(z))*16,-.35,z),scale:[70,.05,.65],angle:Math.sin(z)*.08});this.makeInstances(new THREE.BoxGeometry(1,1,1),material(0xa3d5d4,.3),waves);}
    const mountains=[];for(let z=-100;z<1700;z+=100)for(let side of r.theme==='coast'?[1]:[-1,1])mountains.push({pos:new THREE.Vector3(side*(100+Math.abs(Math.sin(z))*100),20,z),scale:[90,95+Math.abs(Math.sin(z))*80,100]});this.makeInstances(new THREE.ConeGeometry(1,1,7),material(r.theme==='forest'?0x678273:0x7b9a90),mountains);
    this.signalMeshes=[];
    this.game.lesson.signals.forEach((signal,i)=>{const p=this.point(signal.at),g=new THREE.Group();g.position.copy(p).add(new THREE.Vector3(3.1,0,0));g.rotation.y=this.rotation(signal.at);this.environment.add(g);this.addBox([.18,4.5,.18],new THREE.Vector3(0,2.1,0),steel,g);this.addBox([.68,1.9,.36],new THREE.Vector3(0,4.1,0),material(0x172c32),g);const lamps=[];for(let j=0;j<3;j++){const light=new THREE.Mesh(new THREE.CircleGeometry(.17,16),new THREE.MeshBasicMaterial({color:0x293c3c}));light.rotation.y=Math.PI;light.position.set(0,4.7-j*.58,-.19);g.add(light);lamps.push(light);}this.signalMeshes.push({signal,lamps});});
    for(let [i,s] of [0,...this.game.lesson.stops].entries()){const p=this.point(s),g=new THREE.Group();g.position.copy(p);g.rotation.y=this.rotation(s);this.environment.add(g);this.addBox([4,1.2,76],new THREE.Vector3(4.5,.23,-14),concrete,g);this.addBox([.12,.04,76],new THREE.Vector3(2.55,.86,-14),material(0xe4c571),g);this.addBox([4.1,.24,42],new THREE.Vector3(4.5,4.8,-10),material(0x547f81),g);for(let z of [-28,8])this.addBox([.18,4,.18],new THREE.Vector3(4.6,2.7,z),steel,g);const sign=new THREE.Mesh(new THREE.PlaneGeometry(3.2,.8),this.label(i===0?'起點站':`${this.game.route.stationNames[i-1]}站`));sign.rotation.y=Math.PI;sign.position.set(4.5,3.7,8.2);g.add(sign);const stopSign=new THREE.Mesh(new THREE.PlaneGeometry(.8,.8),this.label('停'));stopSign.rotation.y=Math.PI;stopSign.position.set(1.95,1.55,8);g.add(stopSign);this.addBox([.9,.04,.25],new THREE.Vector3(1.5,.2,8),material(0xffd377),g);}
    // Catenary posts create a readable vanishing point; decorative only.
    const poles=[],cross=[];for(let s=0;s<1450;s+=35){const p=this.point(s);p.x-=3.3;poles.push({pos:p.clone().add(new THREE.Vector3(0,3.2,0))});cross.push({pos:p.clone().add(new THREE.Vector3(2.2,6.3,0)),angle:this.rotation(s)});}this.makeInstances(new THREE.BoxGeometry(.14,6.7,.14),steel,poles);this.makeInstances(new THREE.BoxGeometry(4.5,.09,.12),steel,cross);
    this.routeId=this.game.routeId;this.lessonId=this.game.lessonId;
  }
  resize(){const rect=this.canvas.parentElement.getBoundingClientRect();if(rect.width<1||rect.height<1)return;this.renderer.setSize(rect.width,rect.height,false);this.camera.aspect=rect.width/rect.height;this.camera.updateProjectionMatrix();}
  render(){if(this.routeId!==this.game.routeId||this.lessonId!==this.game.lessonId)this.rebuild();const p=this.point(this.game.physics.s),yaw=this.rotation(this.game.physics.s);this.trainRoot.position.copy(p);this.trainRoot.rotation.y=yaw;
    const driver=new THREE.Vector3(0,2.3,8).applyAxisAngle(new THREE.Vector3(0,1,0),yaw).add(p);this.cabRoot.position.copy(driver);this.cabRoot.rotation.y=yaw;
    const cab=this.view==='cab';this.cabRoot.visible=cab;this.trainRoot.visible=!cab;
    if(this.tractionLever)this.tractionLever.rotation.x=this.game.controls.throttle*.08;if(this.brakeLever)this.brakeLever.rotation.x=this.game.controls.brake*.055;
    if(performance.now()-this.instrumentLast>120){this.paintInstruments();this.instrumentLast=performance.now();}
    const location=(cab?new THREE.Vector3(0,1.35,-1):new THREE.Vector3(9,7,-30)).applyAxisAngle(new THREE.Vector3(0,1,0),yaw).add(cab?driver:p);
    this.camera.position.copy(location);const target=(cab?new THREE.Vector3(0,1.3,100):new THREE.Vector3(0,2,0)).applyAxisAngle(new THREE.Vector3(0,1,0),yaw).add(cab?driver:p);this.camera.lookAt(target);
    this.signalMeshes.forEach(({signal,lamps})=>{const aspect=this.game.signalAspect(signal);['red','yellow','green'].forEach((v,i)=>lamps[i].material.color.setHex(v===aspect?{red:0xff5454,yellow:0xffdb59,green:0x63ebba}[v]:0x243435));});this.renderer.render(this.scene,this.camera);
  }
}
